### ISSUE TITLE
How to make the Bot work on a mac?

### ISSUE THREAD

**Issue by s-areal** [cryptotwinsbr/spacecrypto-bot#46]
I´ve installe Python and then runned the following commands:

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py

After that i run

python spacecrypto-bot.py

And i got the following error:

Traceback (most recent call last):
File "spacecrypto-bot.py", line 2, in
from cv2 import cv2
ImportError: No module named cv2

Can anyone help?

**Comment by alanfros** [comment]
after installing pip you need to run the command: 

pip install -r requirements.txt

later u run the: python spacecrypto-bot.py

**Comment by s-areal** [comment]
yes, i forgot to mention that I've already have runned pip install -r requirements.txt
The problem was i had to add 3 to phyton. It boots running python3 spacecrypto-bot.py

It starts but it stalld here and nothing happens.... I already gave permissions for python and terminal to record screen. 
[2022-02-20 22:57:37] [INFO] Connect wallet button detected, logging in!

**Comment by s-areal** [comment]
yep nothing happens

2022-02-20 23:46:21] [INFO] Bot Iniciado. Versao: 1.06
[2022-02-20 23:46:21] [INFO] Qtd naves total: 10
[2022-02-20 23:46:21] [INFO] Qtd naves enviar: 10
[2022-02-20 23:46:21] [INFO] Starting Login
[2022-02-20 23:46:23] [INFO] Connect wallet button detected, logging in!
[2022-02-20 23:47:11] [INFO] Starting Login
[2022-02-20 23:47:13] [INFO] Connect wallet button detected, logging in!

**Comment by bolshoytoster** [comment]
@s-areal I'll set up a mac vm to see if I can reproduce this.

**Comment by Bryandibraga** [comment]
to me shows up [WARNING] No action found.

**Comment by s-areal** [comment]
like i told before  I already gave permissions for python and terminal to record screen. Do you have to gave some kind of permission for controlling the input device (mouse) or something like that? just a tought...

**Comment by bolshoytoster** [comment]
@s-areal the error is because it can't find anything it needs to do. You might have set up spacecrypto (login, go into a 'game') first.

**Comment by s-areal** [comment]
it should click in the button that is detected that should do the login IMO
anyway i logged in manually, all my ships are 100% and it keeps repeating this, but the mouse never moves

[2022-02-21 00:21:16] [INFO] Refresh Spaceship to Fight
[2022-02-21 00:21:27] [INFO] Spaceships sent to Fight: 3
[2022-02-21 00:21:38] [INFO] Spaceships sent to Fight: 6
[2022-02-21 00:21:50] [INFO] Spaceships sent to Fight: 9
[2022-02-21 00:21:55] [INFO] Finish Click ships
[2022-02-21 00:21:57] [INFO] Spaceships sent to Fight: 10
[2022-02-21 00:22:08] [INFO] Refresh Spaceship to Fight
[2022-02-21 00:22:20] [INFO] Spaceships sent to Fight: 3
[2022-02-21 00:22:31] [INFO] Spaceships sent to Fight: 6
[2022-02-21 00:22:43] [INFO] Spaceships sent to Fight: 9
[2022-02-21 00:22:48] [INFO] Finish Click ships

**Comment by bolshoytoster** [comment]
@s-areal if you run
```zsh
python3 -c 'from pyautogui import moveTo
moveTo(0, 0)'
```
in the terminal does your cursor go to the top-left of your screen?
(copy-paste the command including the newline)

**Comment by s-areal** [comment]
I have only 10 ships and already set this in the setting file and made a printscreen of 0/10 and 10/10

**Comment by bolshoytoster** [comment]
@s-areal have you run the command I asked you to?

**Comment by Bryandibraga** [comment]
now my cursor goes to right corner on connect wallet screen

**Comment by bolshoytoster** [comment]
@Bryandibraga what is the output of the bot?

**Comment by s-areal** [comment]
@bolshoytoster
pip install -r requirements.txt - runs ok
then i must type "python3 spacecrypto-bot.py" if i type "python spacecrypto-bot.py" i get the error i+ve posted before:

File "spacecrypto-bot.py", line 2, in
from cv2 import cv2
ImportError: No module named cv2 

And no, the cursor does not move. should i install pip again? 
Should I uses this commands to install PIP

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py

**Comment by bolshoytoster** [comment]
@s-areal what does it say when you run `pip install opencv-python`?

**Comment by Bryandibraga** [comment]
[bolshoytoster](https://github.com/bolshoytoster) what do you mean with output?

**Comment by bolshoytoster** [comment]
@Bryandibraga what does it say in the terminal?

**Comment by s-areal** [comment]
zsh: command not found: pip

**Comment by bolshoytoster** [comment]
@s-areal does `pip3 install opencv-python` work?

**Comment by s-areal** [comment]
I tried installing pip again, please take a look


100 2548k  100 2548k    0     0  6742k      0 --:--:-- --:--:-- --:--:-- 6742k
simaoareal@Mini-de-Simao spacecrypto-bot % python3 get-pip.py


Collecting pip
  Using cached pip-22.0.3-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.3
    Uninstalling pip-22.0.3:
ERROR: Could not install packages due to an OSError: Cannot move the non-empty directory '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip-22.0.3.dist-info/': Lacking write permission to '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip-22.0.3.dist-info/'.

simaoareal@Mini-de-Simao spacecrypto-bot % pip install opencv-python
zsh: command not found: pip
simaoareal@Mini-de-Simao spacecrypto-bot % ls
README.md		debug.py		requirements.txt	spacecrypto-bot.py
__pycache__		get-pip.py		screen_test
debug.log		img_compare		settings.yaml
simaoareal@Mini-de-Simao spacecrypto-bot % cd ..
simaoareal@Mini-de-Simao ~ % pip install opencv-python
zsh: command not found: pip
simaoareal@Mini-de-Simao ~ %

**Comment by Bryandibraga** [comment]
> @Bryandibraga what does it say in the terminal?

[2022-02-20 22:06:54] [INFO] Starting Login
[2022-02-20 22:06:58] [INFO] Connect wallet button detected, logging in!

but teh cursor goes to extreme right bottom corner

**Comment by bolshoytoster** [comment]
@s-areal try running `sudo python3 get-pip.py` to install it.

**Comment by bolshoytoster** [comment]
@Bryandibraga it might be confused by the background; try logging in manually then running the bot.

**Comment by Bryandibraga** [comment]
@bolshoytoster After login in manually the cursor dont moves.

**Comment by bolshoytoster** [comment]
@Bryandibraga what does the terminal say now?

**Comment by s-areal** [comment]
did sudo python3 get-pip.py
did pip install -r requirements.txt

and i get this

Requirement already satisfied: pyobjc-framework-ExternalAccessory==8.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pyobjc->PyAutoGUI==0.9.53->-r requirements.txt (line 5)) (8.2)

**Comment by bolshoytoster** [comment]
@s-areal that's good, try running the bot again.

**Comment by Bryandibraga** [comment]
@bolshoytoster [2022-02-20 22:19:26] [WARNING] No action found

**Comment by s-areal** [comment]
i've tried again. the mouse does not move on the connect wallet. I connect to metamask manually and press play

the mouse does not move and terminal is showing up this

[2022-02-21 01:18:24] [INFO] Spaceships sent to Fight: 3
[2022-02-21 01:18:33] [INFO] Spaceships sent to Fight: 5
[2022-02-21 01:18:43] [INFO] Spaceships sent to Fight: 7
[2022-02-21 01:18:53] [INFO] Spaceships sent to Fight: 9
[2022-02-21 01:18:58] [INFO] Finish Click ships
[2022-02-21 01:19:00] [INFO] Spaceships sent to Fight: 10
[2022-02-21 01:19:13] [INFO] Refresh Spaceship to Fight
[2022-02-21 01:19:23] [INFO] Spaceships sent to Fight: 2

and so one

**Comment by bolshoytoster** [comment]
@Bryandibraga could you make sure nothing blocks the screen (i.e. the terminal window)

**Comment by bolshoytoster** [comment]
@s-areal could you try [this](https://github.com/cryptotwinsbr/spacecrypto-bot/issues/46#issuecomment-1046363865) again please.

**Comment by s-areal** [comment]
the mouse never moved, never
Ive also deleted any "desktops"
terminal is out of the away now

same thing

**Comment by Bryandibraga** [comment]
@bolshoytoster its not

**Comment by s-areal** [comment]
> @s-areal could you try [this](https://github.com/cryptotwinsbr/spacecrypto-bot/issues/46#issuecomment-1046363865) again please.

Does not move

**Comment by s-areal** [comment]
> > @s-areal could you try [this](https://github.com/cryptotwinsbr/spacecrypto-bot/issues/46#issuecomment-1046363865) again please.
> 
> Does not move

I stop the bot, type your command and nothing happens

**Comment by s-areal** [comment]
dont you think this as nothing to do with permissions?

**Comment by s-areal** [comment]
Yeah, the bot detects what is happening, but is not able to do any task...

**Comment by bolshoytoster** [comment]
@s-areal you could try running `sudo python3 spacecrypto-bot.py` to give it root permissions.

**Comment by s-areal** [comment]
i did it and ....t doesn't work

2022-02-21 01:35:29] [INFO] Bot Iniciado. Versao: 1.06
[2022-02-21 01:35:29] [INFO] Qtd naves total: 60
[2022-02-21 01:35:29] [INFO] Qtd naves enviar: 10
[2022-02-21 01:35:32] [WARNING] Nenhuma acao encontrada
[2022-02-21 01:35:33] [WARNING] Nenhuma acao encontrada
[2022-02-21 01:35:33] [WARNING] Nenhuma acao encontrada
[2022-02-21 01:35:34] [WARNING] Nenhuma acao encontrada
[2022-02-21 01:35:34] [INFO] Refresh Spaceship to Fight
[2022-02-21 01:35:45] [INFO] Spaceships sent to Fight: 3
[2022-02-21 01:35:57] [INFO] Spaceships sent to Fight: 6
[2022-02-21 01:36:08] [INFO] Spaceships sent to Fight: 9
[2022-02-21 01:36:14] [INFO] Finish Click ships
[2022-02-21 01:36:16] [INFO] Spaceships sent to Fight: 10
[2022-02-21 01:36:27] [INFO] Refresh Spaceship to Fight
[2022-02-21 01:36:38] [INFO] Spaceships sent to Fight: 3
[2022-02-21 01:37:12] [INFO] Spaceships sent to Fight: 6


the mouse wont move

**Comment by s-areal** [comment]
it doesn't work. Thanks so much for your help... 
I gotta go now, i will see if you reply tommorow.
Thanks again

**Comment by bolshoytoster** [comment]
@s-areal according to [this](https://github.com/cryptotwinsbr/spacecrypto-bot/issues/46#issuecomment-1046363865) reddit post it should create a popup asking to give it permission. You might be able to get it to do the popup again by reinstalling PyAutoGUI: `pip install PyAutoGUI==0.9.53 --ignore-installed`.

**Comment by bolshoytoster** [comment]
The problem I've run into, the default thresholds in `settings.yaml` are too high I'm experimenting with lower amounts to see what will work best.

**Comment by bolshoytoster** [comment]
@Bryandibraga could you change `hard` in `settings.yaml` to 0.25.
