### ISSUE TITLE
[2022-02-21 06:18:50] [WARNING] Nenhuma acao encontrada

### ISSUE THREAD

**Issue by skewliness** [cryptotwinsbr/spacecrypto-bot#47]
why？？？

**Comment by bolshoytoster** [comment]
@skewliness is this an error in the terminal? If so, can you paste the full output of the program here please.

**Comment by hamdialtinbas** [comment]
I had same error. i cannot log in? What is it this problem ?

**Comment by bolshoytoster** [comment]
@hamdialtinbas I believe there is an issue with the default weights in `settings.yaml`. For now you can log in manually.

You might have more luck changing `hard` in `settings.yaml` to `0.25`.

**Comment by hamdialtinbas** [comment]
i changed this parameter. But I log in manuel but i had error
<img width="573" alt="Ekran Resmi 2022-02-23 01 12 32" src="https://user-images.githubusercontent.com/2946108/155228683-ef24c34b-621d-42a7-b414-dd31ddca6abb.png">

**Comment by bolshoytoster** [comment]
@hamdialtinbas can you paste the full error here please.

**Comment by hamdialtinbas** [comment]
[2022-02-23 01:05:23] [INFO] Bot Iniciado. Versao: 1.06
[2022-02-23 01:05:23] [INFO] Qtd naves total: 37
[2022-02-23 01:05:23] [INFO] Qtd naves enviar: 12
[2022-02-23 01:06:30] [INFO] Refresh Spaceship to Fight
[2022-02-23 01:08:57] [INFO] Refresh Spaceship to Fight
Traceback (most recent call last):
  File "spacecrypto-bot.py", line 444, in <module>
    main()
  File "spacecrypto-bot.py", line 425, in main
    refreshSpaceships(0)
  File "spacecrypto-bot.py", line 327, in refreshSpaceships
    scroll(-cda)
  File "spacecrypto-bot.py", line 148, in scroll
    pyautogui.dragRel(0,clickAndDragAmount,duration=1, button='left')
  File "/Users/hamdialtinbas/Library/Python/3.8/lib/python/site-packages/pyautogui/__init__.py", line 598, in wrapper
    returnVal = wrappedFunction(*args, **kwargs)
  File "/Users/hamdialtinbas/Library/Python/3.8/lib/python/site-packages/pyautogui/__init__.py", line 1404, in dragRel
    _mouseMoveDrag("drag", mousex, mousey, xOffset, yOffset, duration, tween, button)
  File "/Users/hamdialtinbas/Library/Python/3.8/lib/python/site-packages/pyautogui/__init__.py", line 1499, in _mouseMoveDrag
    failSafeCheck()
  File "/Users/hamdialtinbas/Library/Python/3.8/lib/python/site-packages/pyautogui/__init__.py", line 1722, in failSafeCheck
    raise FailSafeException(
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False

**Comment by hamdialtinbas** [comment]
my setting.yml


---
  # Valores de configuração do bot
  ship_settings:
    # Quantidade total de naves (total)
    empty_qtd_spaceships: 37
    
    # Quantas naves deseja entrar para o boss
    qtd_send_spaceships: 12

    # Se deseja dar surrender, alterar para o valor do boss (zero não faz)
    boss_surrender: 0
    
    # Envia somente naves 100% (True/False)
    send_ships_full: False

    # Se desejar que remova as naves antes de adicionar outras (True/False)
    remove_ships: False 

    # Volta para a spaceship nas waves 9, 14 e 19
    key_waves: True
    
  # Valor de confiança das comparações
  threshold:
    # Valor padrão: 0.7
    default: 0.7

    # Valor padrão: 0.8
    commom: 0.8
    
    # Valor padrão 0.9
    hard: 0.25

    # Valor padrão: 0.8
    select_wallet_buttons: 0.8

    # Valor padrão: 0.9
    go-fight: 0.9

    # Valor padrão: 0.9
    green_bar: 0.95

    # Valor padrão 0.98
    15-15-ships: 0.98

    # Valor padrão 0.95
    0-15: 0.95

**Comment by bolshoytoster** [comment]
@hamdialtinbas did the mouse go towards the `X` in the top right of your browser window?

**Comment by hamdialtinbas** [comment]
Yes.

**Comment by bolshoytoster** [comment]
@hamdialtinbas try turning `hard` up a bit, I can't test this so you'll have to tweak it until it works. (Turning it down makes it more sensitive, up makes it less sensitive).

**Comment by hamdialtinbas** [comment]
ok. ful screen button cannot work. i will try
